get http://localhost:25800/api/auth/logout HTTP/1.1
content-type: application/json

# {
#     "customer_id": 1,
#     "messenger_id": 4,
#     "receiver":"123/334 KKAKSJDK ajkdmzx 1292 ",
#     "cost":123342,
#     "api_key":"my_doggo_name_jeff"
# }

{
    "username": "messenger12",
    "password": "123456",
    "name":"kpun nongming",
    "email":"cmesssaldj3@hotmail.com",
    "tel":"0152983589",
    "address":"559/10 latkrabang bangkok 10520",
    "gender":"female",
    "order_manager_id":2,
    "supervisor_id":1,
    "register_type":"messenger",
    "secret_key":"test",
    "api_key":"my_doggo_name_jeff"
}
