const url = {
    resgister:'http://localhost:25800/api/auth/register',
    login:'http://localhost:25800/api/auth/login',
    session:'http://localhost:25800/api/auth/get/session',
    logout:'http://localhost:25800/api/auth/logout',
    customer:{
        createRequest:'http://localhost:25800/api/request/createRequest',
        getAllRequestByCustomerId:'http://localhost:25800/api/request/getAllRequestByCustomerId',
        deleteRequestById:'http://localhost:25800/api/request/deleteRequestById/',
        editRequestById:'http://localhost:25800/api/request/editRequest/',
        getOrdersHistory:'http://localhost:25800/api/orders/get/history/customer'
    },
    contacts:{
        sendMessage:'http://localhost:25800/api/contacts/sendMessage',
        getMessageBySender:'http://localhost:25800/api/contacts/getMessageBySender',
        getMessageByReceiver:'http://localhost:25800/api/contacts/getMessageByReceiver',
        updateMessageStatus:'http://localhost:25800/api/contacts/updateMessageStatus',
        getNameById:'http://localhost:25800/api/contacts/getName/',
        getUnReadMessageByReceiver:'http://localhost:25800/api/contacts/getUnReadMessageByReceiver'
    },
    Goods:{
        createGoods:'http://localhost:25800/api/goods/create',
        editGoodsById:'http://localhost:25800/api/goods/edit/',
        getGoodsById:'http://localhost:25800/api/goods/by/id/',
        getGoodsByOrderId:'http://localhost:25800/api/goods/by/order/',
        deleteGoodsById:'http://localhost:25800/api/goods/by/id/',
        deleteGoodsByOrderId:'http://localhost:25800/api/goods/by/order/'
    },
    Operator:{
        getRequestByOperatorId:'http://localhost:25800/api/request/getAllRequestByOperatorId',
        updateRequestStatus:'http://localhost:25800/api/request/updateStatus/',
        getCompletedRequestCount:'http://localhost:25800/api/request/getCompletedRequestCount'
    },
    Order:{
        getOrderByRequestId:'http://localhost:25800/api/orders/get/request/',
        createOrder:'http://localhost:25800/api/orders/create',
        getOrderById:'http://localhost:25800/api/orders/get/',
        editOrderById:'http://localhost:25800/api/orders/edit/',
        deleteOrderById:'http://localhost:25800/api/orders/delete/'
    },
    Schedule:{
        createSchedule:'http://localhost:25800/api/schedule/createSchedule',
        getScheduleByOrder:'http://localhost:25800/api/schedule/getByOrder/',
        getScheduleById:'http://localhost:25800/api/schedule/getById/',
        getScheduleInProgressDetail:'http://localhost:25800/api/schedule/getScheduleInProgressDetail',
        getAllDriver:'http://localhost:25800/api/schedule/getAllDriver',
        updateScheduleDriver:'http://localhost:25800/api/schedule/updateScheduleDriver/',
        updateScheduleVehicle:'http://localhost:25800/api/schedule/updateScheduleVehicle/',
        getScheduleCompletedDetail:'http://localhost:25800/api/schedule/getScheduleCompletedDetail',
        getScheduleInProgressDetailByDriver:'http://localhost:25800/api/schedule/getScheduleInProgressDetailByDriver',
        updateScheduleStatus:'http://localhost:25800/api/schedule/updateScheduleStatus/',
        getScheduleCompletedDetailByDriver:'http://localhost:25800/api/schedule/getScheduleCompletedDetailByDriver',
        getScheduleDetailByShipping:'http://localhost:25800/api/schedule/getScheduleDetailByShipping'
    },
    Vehicle:{
        getAllVehicleByManagerId:'http://localhost:25800/api/vehicle/getAllVehicleByManagerId',
        addVehicle:'http://localhost:25800/api/vehicle/addVehicle',
        deleteVehicle:'http://localhost:25800/api/vehicle/deleteVehicle/',
        updateVehicleStatus:'http://localhost:25800/api/vehicle/updateVehicleStatus',
        editVehicle:'http://localhost:25800/api/vehicle/editVehicle'
    },
    Location:{
        addLocation:'http://localhost:25800/api/location/addLocation',
        getLocationByOrderId:'http://localhost:25800/api/location/getLocationByOrderId/'
    },
    Supervisor:{
        getStaffDetail:'http://localhost:25800/api/user/getStaffDetail',
        getLatestFeedback:'http://localhost:25800/api/feedback/getLatestFeedback'
    },
    Feedback:{
        createFeedback:'http://localhost:25800/api/feedback/createFeedback'
    },
    Dashboard:{
        CustomerAndOperator:'http://localhost:25800/api/user/dashboard/customerAndOperator'
    }
}

export default url
