const express = require('express')
const router = express.Router()
const ScheduleController = require('../controller/ScheduleController')
const uploader = require('../uploader/DocumentUploader')
router.post('/createSchedule', uploader.none(), ScheduleController.createSchedule)
router.get('/getByOrder/:id', ScheduleController.getScheduleByOrder)
router.get('/getById/:id', ScheduleController.getScheduleById)
router.get('/getScheduleInProgressDetail', ScheduleController.getScheduleInProgressDetail)
router.get('/getScheduleCompletedDetail', ScheduleController.getScheduleCompletedDetail)
router.get('/getAllDriver', ScheduleController.getAllDriver)
router.put('/updateScheduleDriver/:id', uploader.none(), ScheduleController.updateScheduleDriver)
router.put('/updateScheduleVehicle/:id', uploader.none(), ScheduleController.updateScheduleVehicle)
router.get('/getScheduleInProgressDetailByDriver', ScheduleController.getScheduleInProgressDetailByDriver)
router.put('/updateScheduleStatus/:id', uploader.none(), ScheduleController.updateScheduleStatus)
router.get('/getScheduleCompletedDetailByDriver', ScheduleController.getScheduleCompletedDetailByDriver)
router.get('/getScheduleDetailByShipping', ScheduleController.getScheduleDetailByShipping)
router.put('/editPickupSchedule/:id', uploader.none(), ScheduleController.editPickupSchedule)
module.exports = router
